# Generated by Django 3.0.8 on 2020-09-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_auto_20200705_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='affiliate',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
