# Generated by Django 3.0.8 on 2020-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text="Generated by Stripe's API", max_length=128, null=True, verbose_name='Stripe session id'),
        ),
    ]
